server:
  port: 3000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehsan
    username: ehsan
    password: 123
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  #    database: postgresql
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: NEVER

logging:
  file:
    name: app.log
    max-size: 10MB
    max-history: 100
    total-size-cap: 10GB

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus'
  endpoint:
    health:
      show-details: ALWAYS
    info:
      enabled: true


info:
  app:
    name: Ehsan


