server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
  port: 3000

spring:
  datasource:
    password: 123
    url: 'jdbc:postgresql://localhost:5432/ehsan'
    username: ehsan
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  output:
    ansi:
      enabled: always


logging:
  file:
    max-history: 100
    max-size: 10MB
    name: app.log
    total-size-cap: 10GB

management:
  endpoint:
    health:
      show-details: ALWAYS
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: 'Ehsan'
  seeder:
    superadmin:
      first_name: "Ehsan"
      last_name: "Shavandi"
      email: "superadmin@ehsan.edu"
      password: "123"
      role: "ADMIN"

